name: Deploy Application

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: yarn-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --cwd packages/frontend

      - name: Test application
        working-directory: packages/frontend
        run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: yarn-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --cwd packages/frontend

      - name: Lint application
        working-directory: packages/frontend
        run: yarn lint
